# Generated by Django 4.1.1 on 2022-10-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bears", "0002_alter_bear_bear_name_alter_bear_bear_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_uuid", models.UUIDField(blank=True, null=True)),
                ("competition_year", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="round",
            name="year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bears.year",
            ),
        ),
    ]
