# Generated by Django 4.1.1 on 2022-10-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bears", "0003_year_round_year"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="round",
            unique_together={("year", "round_number")},
        ),
        migrations.RemoveField(
            model_name="round",
            name="competition_year",
        ),
    ]
